# Generated by Django 6.0 on 2026-05-08 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Creado'), ('updated', 'Actualizado')], max_length=20)),
                ('changed_fields', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='facturacion.product')),
            ],
            options={
                'verbose_name': 'Historial de Producto',
                'verbose_name_plural': 'Historiales de Productos',
                'ordering': ['-timestamp'],
            },
        ),
    ]
