# Generated by Django 5.2.7 on 2025-11-14 21:38

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría de Activo',
                'verbose_name_plural': 'Categorías de Activos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Serie')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('in_use', 'En Uso'), ('maintenance', 'En Mantenimiento'), ('damaged', 'Dañado'), ('retired', 'Dado de Baja')], default='available', max_length=20, verbose_name='Estado')),
                ('condition', models.CharField(choices=[('excellent', 'Excelente'), ('good', 'Bueno'), ('fair', 'Regular'), ('poor', 'Malo')], default='good', max_length=20, verbose_name='Condición')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ubicación')),
                ('assigned_to', models.CharField(blank=True, max_length=200, null=True, verbose_name='Asignado a')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio de Compra')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Compra')),
                ('warranty_expiry', models.DateField(blank=True, null=True, verbose_name='Vencimiento de Garantía')),
                ('last_maintenance', models.DateField(blank=True, null=True, verbose_name='Último Mantenimiento')),
                ('next_maintenance', models.DateField(blank=True, null=True, verbose_name='Próximo Mantenimiento')),
                ('maintenance_notes', models.TextField(blank=True, null=True, verbose_name='Notas de Mantenimiento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas Adicionales')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='facturacion.assetcategory', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Activo',
                'verbose_name_plural': 'Activos',
                'ordering': ['-created_at'],
            },
        ),
    ]
