# Generated by Django 5.2.1 on 2025-10-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_stock',
            field=models.IntegerField(blank=True, default=5, null=True, verbose_name='Stock Mínimo'),
        ),
    ]
