# Generated by Django 4.2.19 on 2025-04-08 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='customer',
        ),
        migrations.AddField(
            model_name='sale',
            name='mechanic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='facturacion.mechanic'),
            preserve_default=False,
        ),
    ]
