# Generated by Django 5.2.1 on 2025-10-20 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_product_min_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='min_stock',
            field=models.IntegerField(blank=True, default=3, null=True, verbose_name='Stock Mínimo'),
        ),
    ]
