# Generated by Django 4.2.19 on 2025-05-07 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_remove_labour_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='labour',
            name='factura_asociada',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
