# Generated by Django 6.0 on 2026-05-08 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_producthistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-created_at'], 'verbose_name': 'Factura', 'verbose_name_plural': 'Facturas'},
        ),
        migrations.AddField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('frequent', 'Frecuente'), ('occasional', 'Ocasional')], default='occasional', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='ruc_ci',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RUC/CI'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='facturacion.client', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Descuento'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='N° Factura'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Efectivo'), ('card', 'Tarjeta'), ('transfer', 'Transferencia'), ('mixed', 'Mixto')], default='cash', max_length=20, verbose_name='Método de Pago'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagada'), ('cancelled', 'Anulada'), ('refunded', 'Reembolsada')], default='pending', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Subtotal'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='IVA'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='cash_received',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Efectivo Recibido'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='change',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Cambio'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='receipt_type',
            field=models.CharField(choices=[('ticket', 'Ticket'), ('invoice', 'Factura')], default='invoice', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total'),
        ),
    ]
