# Generated by Django 6.0 on 2026-05-09 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_alter_invoice_options_client_client_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Efectivo'), ('efectivo', 'Efectivo'), ('card', 'Tarjeta'), ('tarjeta', 'Tarjeta'), ('transfer', 'Transferencia'), ('transferencia', 'Transferencia')], default='cash', max_length=20, verbose_name='Método de Pago'),
        ),
    ]
