# Generated by Django 6.0 on 2026-05-10 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_alter_invoice_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='receipt_type',
            field=models.CharField(choices=[('ticket', 'Ticket'), ('invoice', 'Factura')], default='invoice', max_length=20, verbose_name='Tipo de Comprobante'),
        ),
    ]
