# Generated by Django 6.0 on 2026-05-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0005_alter_invoice_receipt_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Efectivo'), ('card', 'Tarjeta'), ('transfer', 'Transferencia')], default='cash', max_length=20, verbose_name='Método de Pago'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='receipt_type',
            field=models.CharField(choices=[('ticket', 'Ticket (Venta Rápida)'), ('invoice', 'Factura (Completa)')], default='invoice', max_length=20, verbose_name='Tipo de Comprobante'),
        ),
    ]
