# Generated by Django 6.0 on 2026-05-25 02:39

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0007_sale_view_sale_totals_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbonoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_abono', models.DateTimeField(default=django.utils.timezone.now)),
                ('notas', models.TextField(blank=True, null=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Abono',
                'verbose_name_plural': 'Abonos',
                'ordering': ['-fecha_abono'],
            },
        ),
        migrations.CreateModel(
            name='ServicioManoObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_persona', models.CharField(max_length=70)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('factura_asociada', models.CharField(blank=True, max_length=10, null=True)),
                ('modalidad_pago', models.CharField(choices=[('contado', 'Contado'), ('credito', 'Crédito')], default='contado', max_length=10)),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcialmente Pagado'), ('pagado', 'Pagado')], default='pendiente', max_length=10)),
                ('total_abonado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Servicio de Mano de Obra',
                'verbose_name_plural': 'Servicios de Mano de Obra',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.DeleteModel(
            name='Labour',
        ),
        migrations.AddField(
            model_name='abonoservicio',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos', to='facturacion.serviciomanoobra'),
        ),
    ]
