# Generated by Django 6.0 on 2026-05-25 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0008_abonoservicio_serviciomanoobra_delete_labour_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ECFIssuerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=150, verbose_name='Razón Social')),
                ('trade_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre Comercial')),
                ('rnc', models.CharField(max_length=11, unique=True, verbose_name='RNC Emisor')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('municipality', models.CharField(blank=True, max_length=80, null=True, verbose_name='Municipio')),
                ('province', models.CharField(blank=True, max_length=80, null=True, verbose_name='Provincia')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo')),
                ('environment', models.CharField(choices=[('testing', 'Pruebas'), ('certification', 'Certificacion'), ('production', 'Produccion')], default='testing', max_length=20, verbose_name='Ambiente DGII')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración e-CF del Emisor',
                'verbose_name_plural': 'Configuraciones e-CF del Emisor',
                'ordering': ['-is_active', 'business_name'],
            },
        ),
        migrations.CreateModel(
            name='ECFSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecf_type', models.CharField(choices=[('31', 'Factura de Crédito Fiscal Electrónica'), ('32', 'Factura de Consumo Electrónica'), ('33', 'Nota de Débito Electrónica'), ('34', 'Nota de Crédito Electrónica'), ('41', 'Compras Electrónico'), ('43', 'Gastos Menores Electrónico'), ('44', 'Regímenes Especiales Electrónico'), ('45', 'Gubernamental Electrónico'), ('46', 'Exportaciones Electrónico'), ('47', 'Pagos al Exterior Electrónico')], max_length=2, verbose_name='Tipo e-CF')),
                ('start_number', models.PositiveBigIntegerField(verbose_name='Secuencia Inicial')),
                ('end_number', models.PositiveBigIntegerField(verbose_name='Secuencia Final')),
                ('next_number', models.PositiveBigIntegerField(verbose_name='Próxima Secuencia')),
                ('authorization_date', models.DateField(blank=True, null=True, verbose_name='Fecha Autorización')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Fecha Vencimiento')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ecf_sequences', to='facturacion.ecfissuerconfig', verbose_name='Emisor')),
            ],
            options={
                'verbose_name': 'Secuencia e-NCF',
                'verbose_name_plural': 'Secuencias e-NCF',
                'ordering': ['ecf_type', 'start_number'],
            },
        ),
        migrations.CreateModel(
            name='ElectronicFiscalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecf_type', models.CharField(choices=[('31', 'Factura de Crédito Fiscal Electrónica'), ('32', 'Factura de Consumo Electrónica'), ('33', 'Nota de Débito Electrónica'), ('34', 'Nota de Crédito Electrónica'), ('41', 'Compras Electrónico'), ('43', 'Gastos Menores Electrónico'), ('44', 'Regímenes Especiales Electrónico'), ('45', 'Gubernamental Electrónico'), ('46', 'Exportaciones Electrónico'), ('47', 'Pagos al Exterior Electrónico')], max_length=2, verbose_name='Tipo e-CF')),
                ('encf', models.CharField(max_length=13, unique=True, verbose_name='e-NCF')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('xml_generated', 'XML Generado'), ('signed', 'Firmado'), ('submitted', 'Enviado a DGII'), ('accepted', 'Aceptado'), ('rejected', 'Rechazado'), ('cancelled', 'Anulado')], default='draft', max_length=20, verbose_name='Estado')),
                ('track_id', models.CharField(blank=True, max_length=80, null=True, verbose_name='TrackID DGII')),
                ('xml_content', models.TextField(blank=True, null=True, verbose_name='XML')),
                ('signed_xml_content', models.TextField(blank=True, null=True, verbose_name='XML Firmado')),
                ('dgii_response', models.JSONField(blank=True, null=True, verbose_name='Respuesta DGII')),
                ('last_submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Último Envío')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Aceptación')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Motivo Rechazo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='electronic_document', to='facturacion.invoice', verbose_name='Factura')),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='electronic_documents', to='facturacion.ecfissuerconfig', verbose_name='Emisor')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='electronic_documents', to='facturacion.ecfsequence', verbose_name='Secuencia')),
            ],
            options={
                'verbose_name': 'Documento Fiscal Electrónico',
                'verbose_name_plural': 'Documentos Fiscales Electrónicos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ECFEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Creado'), ('xml_generated', 'XML Generado'), ('signed', 'Firmado'), ('submitted', 'Enviado'), ('status_checked', 'Estado Consultado'), ('accepted', 'Aceptado'), ('rejected', 'Rechazado'), ('cancelled', 'Anulado'), ('error', 'Error')], max_length=30)),
                ('message', models.TextField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('electronic_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='facturacion.electronicfiscaldocument')),
            ],
            options={
                'verbose_name': 'Evento e-CF',
                'verbose_name_plural': 'Eventos e-CF',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='ecfsequence',
            constraint=models.UniqueConstraint(fields=('issuer', 'ecf_type', 'start_number', 'end_number'), name='unique_ecf_sequence_range'),
        ),
    ]
