# Generated by Django 6.0 on 2026-05-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0009_ecfissuerconfig_ecfsequence_electronicfiscaldocument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronicfiscaldocument',
            name='dgii_request_xml',
            field=models.TextField(blank=True, null=True, verbose_name='Request DGII'),
        ),
        migrations.AddField(
            model_name='electronicfiscaldocument',
            name='dgii_response_xml',
            field=models.TextField(blank=True, null=True, verbose_name='Response DGII'),
        ),
        migrations.AddField(
            model_name='electronicfiscaldocument',
            name='last_status_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última Consulta Estado'),
        ),
        migrations.AlterField(
            model_name='electronicfiscaldocument',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('xml_generated', 'XML Generado'), ('signed', 'Firmado'), ('pending', 'Pendiente DGII'), ('submitted', 'Enviado a DGII'), ('processing', 'En Proceso DGII'), ('accepted', 'Aceptado'), ('rejected', 'Rechazado'), ('error', 'Error DGII'), ('cancelled', 'Anulado')], default='draft', max_length=20, verbose_name='Estado'),
        ),
    ]
