# Generated by Django 6.0 on 2026-05-29 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0012_fiscal_hardening_credit_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecfeventlog',
            name='event_type',
            field=models.CharField(choices=[('created', 'Creado'), ('queued', 'Encolado'), ('xml_generated', 'XML Generado'), ('signed', 'Firmado'), ('submitted', 'Enviado'), ('status_checked', 'Estado Consultado'), ('retry_scheduled', 'Reintento Programado'), ('skipped', 'Omitido'), ('accepted', 'Aceptado'), ('rejected', 'Rechazado'), ('cancelled', 'Anulado'), ('error', 'Error')], max_length=30),
        ),
        migrations.AlterField(
            model_name='electronicfiscaldocument',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('queued', 'En Cola'), ('xml_generated', 'XML Generado'), ('signed', 'Firmado'), ('pending', 'Pendiente DGII'), ('submitted', 'Enviado a DGII'), ('processing', 'En Proceso DGII'), ('accepted', 'Aceptado'), ('rejected', 'Rechazado'), ('error', 'Error DGII'), ('cancelled', 'Anulado')], default='draft', max_length=20, verbose_name='Estado'),
        ),
    ]
