# Generated by Django 6.0 on 2026-06-06 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_default_company(apps, schema_editor):
    Company = apps.get_model('facturacion', 'Company')
    CompanyMembership = apps.get_model('facturacion', 'CompanyMembership')
    ECFIssuerConfig = apps.get_model('facturacion', 'ECFIssuerConfig')
    User = apps.get_model('auth', 'User')

    issuer = ECFIssuerConfig.objects.order_by('-is_active', 'id').first()
    if issuer:
        name = issuer.trade_name or issuer.business_name
        company_values = {
            'name': name or 'Empresa Principal',
            'legal_name': issuer.business_name or name or 'Empresa Principal',
            'rnc': issuer.rnc or '',
            'email': issuer.email or None,
            'phone': issuer.phone or '',
            'address': issuer.address or '',
            'is_active': True,
        }
    else:
        company_values = {
            'name': 'Empresa Principal',
            'legal_name': 'Empresa Principal',
            'rnc': '',
            'email': None,
            'phone': '',
            'address': 'Direccion pendiente',
            'is_active': True,
        }

    company, _created = Company.objects.get_or_create(
        rnc=company_values['rnc'],
        defaults=company_values,
    ) if company_values['rnc'] else Company.objects.get_or_create(
        name=company_values['name'],
        defaults=company_values,
    )

    for user in User.objects.all():
        if user.is_superuser and user.is_active:
            role = 'owner'
            is_active = True
        elif user.is_staff and user.is_active:
            role = 'admin'
            is_active = True
        elif user.is_active:
            role = 'cashier'
            is_active = True
        else:
            role = 'readonly'
            is_active = False

        CompanyMembership.objects.get_or_create(
            user=user,
            company=company,
            defaults={'role': role, 'is_active': is_active},
        )


def unseed_default_company(apps, schema_editor):
    Company = apps.get_model('facturacion', 'Company')
    Company.objects.filter(name='Empresa Principal').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0019_invoice_view_financial_totals_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('legal_name', models.CharField(blank=True, default='', max_length=150)),
                ('rnc', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('address', models.TextField(blank=True, default='')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='companies/logos/')),
                ('primary_color', models.CharField(blank=True, default='', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('supervisor', 'Supervisor'), ('cashier', 'Cajero'), ('accountant', 'Contador'), ('readonly', 'Solo lectura')], default='cashier', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='facturacion.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membresía de empresa',
                'verbose_name_plural': 'Membresías de empresa',
                'ordering': ['company__name', 'user__username'],
                'constraints': [models.UniqueConstraint(fields=('user', 'company'), name='unique_company_membership_user_company')],
            },
        ),
        migrations.RunPython(seed_default_company, unseed_default_company),
    ]
