# Generated by Django 6.0 on 2026-06-06 04:57

import django.db.models.deletion
from django.db import migrations, models


LOW_RISK_MODEL_NAMES = [
    'Client',
    'Category',
    'Product',
    'Almacen',
    'AssetCategory',
    'Asset',
    'ServicioManoObra',
    'AbonoServicio',
]


def assign_default_company(apps, schema_editor):
    Company = apps.get_model('facturacion', 'Company')
    default_company = Company.objects.order_by('id').first()
    if not default_company:
        default_company = Company.objects.create(
            name='Empresa Principal',
            legal_name='Empresa Principal',
            rnc='000000000',
            is_active=True,
        )

    for model_name in LOW_RISK_MODEL_NAMES:
        model = apps.get_model('facturacion', model_name)
        model.objects.filter(company__isnull=True).update(company=default_company)


def unassign_default_company(apps, schema_editor):
    for model_name in LOW_RISK_MODEL_NAMES:
        model = apps.get_model('facturacion', model_name)
        model.objects.update(company=None)


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0020_company_companymembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonoservicio',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='abonos_servicio', to='facturacion.company'),
        ),
        migrations.AddField(
            model_name='almacen',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='almacenes', to='facturacion.company'),
        ),
        migrations.AddField(
            model_name='asset',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='facturacion.company'),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_categories', to='facturacion.company'),
        ),
        migrations.AddField(
            model_name='category',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='facturacion.company'),
        ),
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='facturacion.company'),
        ),
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='facturacion.company'),
        ),
        migrations.AddField(
            model_name='serviciomanoobra',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicios_mano_obra', to='facturacion.company'),
        ),
        migrations.RunPython(assign_default_company, unassign_default_company),
    ]
