# Generated by Django 6.0 on 2026-06-06 05:07

from django.db import migrations, models
from django.db.models import Count


UNIQUE_CHECKS = [
    ('Almacen', 'name', 'unique_almacen_name_per_company', False),
    ('Asset', 'code', 'unique_asset_code_per_company', False),
    ('AssetCategory', 'name', 'unique_asset_category_name_per_company', False),
    ('Category', 'name', 'unique_category_name_per_company', False),
    ('Client', 'ruc_ci', 'unique_client_ruc_ci_per_company', True),
    ('Product', 'barcode', 'unique_product_barcode_per_company', True),
]


def validate_company_scoped_duplicates(apps, schema_editor):
    conflicts = []
    for model_name, field_name, constraint_name, ignore_blank in UNIQUE_CHECKS:
        model = apps.get_model('facturacion', model_name)
        queryset = model.objects.filter(company__isnull=False)
        if ignore_blank:
            queryset = queryset.exclude(**{f'{field_name}__isnull': True}).exclude(**{field_name: ''})

        duplicates = (
            queryset
            .values('company_id', field_name)
            .annotate(total=Count('id'))
            .filter(total__gt=1)
        )
        for duplicate in duplicates[:10]:
            conflicts.append(
                f"{constraint_name}: company_id={duplicate['company_id']} "
                f"{field_name}={duplicate[field_name]!r} total={duplicate['total']}"
            )

    if conflicts:
        raise RuntimeError(
            "No se pueden aplicar constraints multiempresa por duplicados existentes. "
            "Resolver primero: " + "; ".join(conflicts)
        )


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0021_abonoservicio_company_almacen_company_asset_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='code',
            field=models.CharField(max_length=50, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código de Barras'),
        ),
        migrations.RunPython(validate_company_scoped_duplicates, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='almacen',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', False)), fields=('company', 'name'), name='unique_almacen_name_per_company'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', False)), fields=('company', 'code'), name='unique_asset_code_per_company'),
        ),
        migrations.AddConstraint(
            model_name='assetcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', False)), fields=('company', 'name'), name='unique_asset_category_name_per_company'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', False)), fields=('company', 'name'), name='unique_category_name_per_company'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', False), ('ruc_ci__isnull', False), models.Q(('ruc_ci', ''), _negated=True)), fields=('company', 'ruc_ci'), name='unique_client_ruc_ci_per_company'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', False), ('barcode__isnull', False), models.Q(('barcode', ''), _negated=True)), fields=('company', 'barcode'), name='unique_product_barcode_per_company'),
        ),
    ]
