# Generated by Django 6.0 on 2026-06-06 05:22

import django.db.models.deletion
from django.db import migrations, models


def assign_commercial_companies(apps, schema_editor):
    Company = apps.get_model('facturacion', 'Company')
    Invoice = apps.get_model('facturacion', 'Invoice')
    Quotation = apps.get_model('facturacion', 'Quotation')
    default_company = Company.objects.order_by('id').first()
    if not default_company:
        default_company = Company.objects.create(
            name='Empresa Principal',
            legal_name='Empresa Principal',
            rnc='000000000',
            is_active=True,
        )

    for quotation in Quotation.objects.select_related('client').filter(company__isnull=True).iterator():
        company = getattr(quotation.client, 'company', None) or default_company
        quotation.company = company
        quotation.save(update_fields=['company'])

    for invoice in Invoice.objects.select_related('client', 'origin_quotation').filter(company__isnull=True).iterator():
        company = (
            getattr(invoice.origin_quotation, 'company', None)
            or getattr(invoice.client, 'company', None)
            or default_company
        )
        invoice.company = company
        invoice.save(update_fields=['company'])

    if Invoice.objects.filter(company__isnull=True).exists() or Quotation.objects.filter(company__isnull=True).exists():
        raise RuntimeError("La migracion multiempresa comercial dejo facturas o cotizaciones sin company.")


def unassign_commercial_companies(apps, schema_editor):
    apps.get_model('facturacion', 'Invoice').objects.update(company=None)
    apps.get_model('facturacion', 'Quotation').objects.update(company=None)


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0022_alter_asset_code_alter_assetcategory_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='facturacion.company'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='facturacion.company'),
        ),
        migrations.RunPython(assign_commercial_companies, unassign_commercial_companies),
    ]
