# Generated by Django 6.0 on 2026-06-06 18:50

import django.db.models.deletion
from django.db import migrations, models


def assign_credit_note_companies(apps, schema_editor):
    Company = apps.get_model('facturacion', 'Company')
    CreditNote = apps.get_model('facturacion', 'CreditNote')
    default_company = Company.objects.order_by('id').first()
    if not default_company:
        default_company = Company.objects.create(
            name='Empresa Principal',
            legal_name='Empresa Principal',
            rnc='000000000',
            is_active=True,
        )

    for note in CreditNote.objects.select_related('origin_invoice').filter(company__isnull=True).iterator():
        note.company = getattr(note.origin_invoice, 'company', None) or default_company
        note.save(update_fields=['company'])

    if CreditNote.objects.filter(company__isnull=True).exists():
        raise RuntimeError("La migracion multiempresa E34 dejo notas de credito sin company.")


def unassign_credit_note_companies(apps, schema_editor):
    apps.get_model('facturacion', 'CreditNote').objects.update(company=None)


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0023_invoice_company_quotation_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='facturacion.company'),
        ),
        migrations.RunPython(assign_credit_note_companies, unassign_credit_note_companies),
    ]
