# Generated by Django 6.0 on 2026-06-06 19:34

import django.db.models.deletion
from django.db import migrations, models


def assign_ecf_config_companies(apps, schema_editor):
    Company = apps.get_model('facturacion', 'Company')
    ECFIssuerConfig = apps.get_model('facturacion', 'ECFIssuerConfig')
    ECFSequence = apps.get_model('facturacion', 'ECFSequence')
    default_company = Company.objects.order_by('id').first()
    if not default_company:
        default_company = Company.objects.create(
            name='Empresa Principal',
            legal_name='Empresa Principal',
            rnc='000000000',
            is_active=True,
        )

    ECFIssuerConfig.objects.filter(company__isnull=True).update(company=default_company)
    for sequence in ECFSequence.objects.select_related('issuer').filter(company__isnull=True).iterator():
        sequence.company = getattr(sequence.issuer, 'company', None) or default_company
        sequence.save(update_fields=['company'])

    if ECFIssuerConfig.objects.filter(company__isnull=True).exists() or ECFSequence.objects.filter(company__isnull=True).exists():
        raise RuntimeError("La migracion multiempresa fiscal dejo emisores o secuencias sin company.")


def unassign_ecf_config_companies(apps, schema_editor):
    apps.get_model('facturacion', 'ECFSequence').objects.update(company=None)
    apps.get_model('facturacion', 'ECFIssuerConfig').objects.update(company=None)


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0024_creditnote_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecfissuerconfig',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ecf_issuers', to='facturacion.company'),
        ),
        migrations.AddField(
            model_name='ecfsequence',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ecf_sequences', to='facturacion.company'),
        ),
        migrations.RunPython(assign_ecf_config_companies, unassign_ecf_config_companies),
    ]
