# Generated by Django 6.0 on 2026-06-06 20:01

import django.db.models.deletion
from django.db import migrations, models


def assign_electronic_document_companies(apps, schema_editor):
    Company = apps.get_model('facturacion', 'Company')
    ElectronicFiscalDocument = apps.get_model('facturacion', 'ElectronicFiscalDocument')

    default_company = Company.objects.order_by('id').first()
    if not default_company:
        default_company = Company.objects.create(
            name='Empresa Principal',
            legal_name='Empresa Principal',
            rnc='000000000',
            is_active=True,
        )

    documents = (
        ElectronicFiscalDocument.objects
        .select_related('invoice', 'credit_note', 'issuer')
        .filter(company__isnull=True)
    )
    for document in documents.iterator():
        company = None
        if document.invoice_id and getattr(document.invoice, 'company_id', None):
            company = document.invoice.company
        elif document.credit_note_id and getattr(document.credit_note, 'company_id', None):
            company = document.credit_note.company
        elif document.issuer_id and getattr(document.issuer, 'company_id', None):
            company = document.issuer.company
        else:
            company = default_company
        document.company = company
        document.save(update_fields=['company'])

    if ElectronicFiscalDocument.objects.filter(company__isnull=True).exists():
        raise RuntimeError("La migracion multiempresa fiscal dejo documentos e-CF sin company.")


def unassign_electronic_document_companies(apps, schema_editor):
    apps.get_model('facturacion', 'ElectronicFiscalDocument').objects.update(company=None)


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0025_ecfissuerconfig_company_ecfsequence_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronicfiscaldocument',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='electronic_fiscal_documents', to='facturacion.company'),
        ),
        migrations.RunPython(assign_electronic_document_companies, unassign_electronic_document_companies),
    ]
