# Generated by Django 6.0 on 2026-06-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0034_number_sequence_company_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecfissuerconfig',
            name='certificate_fingerprint',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Huella SHA-256 Certificado'),
        ),
        migrations.AddField(
            model_name='ecfissuerconfig',
            name='certificate_issuer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Emisor Certificado'),
        ),
        migrations.AddField(
            model_name='ecfissuerconfig',
            name='certificate_not_valid_after',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Certificado Válido Hasta'),
        ),
        migrations.AddField(
            model_name='ecfissuerconfig',
            name='certificate_not_valid_before',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Certificado Válido Desde'),
        ),
        migrations.AddField(
            model_name='ecfissuerconfig',
            name='certificate_serial_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Serie Certificado'),
        ),
        migrations.AddField(
            model_name='ecfissuerconfig',
            name='certificate_status',
            field=models.CharField(choices=[('missing', 'Faltante'), ('active', 'Activo'), ('expiring_soon', 'Por vencer'), ('expired', 'Vencido'), ('invalid', 'Inválido')], default='missing', max_length=20, verbose_name='Estado Certificado'),
        ),
        migrations.AddField(
            model_name='ecfissuerconfig',
            name='certificate_status_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Actualizado Certificado'),
        ),
        migrations.AddField(
            model_name='ecfissuerconfig',
            name='certificate_subject',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Asunto Certificado'),
        ),
    ]
