# Generated by Django 6.0 on 2026-06-12 05:13

from django.db import migrations, models


def backfill_existing_invoices(apps, schema_editor):
    Invoice = apps.get_model('facturacion', 'Invoice')
    for invoice in Invoice.objects.filter(inventory_committed_at__isnull=True).only('id', 'created_at', 'updated_at').iterator():
        invoice.inventory_committed_at = invoice.updated_at or invoice.created_at
        invoice.save(update_fields=['inventory_committed_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0038_alter_client_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='inventory_committed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inventario comprometido'),
        ),
        migrations.RunPython(backfill_existing_invoices, migrations.RunPython.noop),
    ]
