# Generated by Django 6.0 on 2026-06-13 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0039_invoice_inventory_committed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecfissuerconfig',
            name='certificate_rnc_detected',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='RNC Detectado en Certificado'),
        ),
        migrations.AddField(
            model_name='ecfissuerconfig',
            name='certificate_rnc_match_status',
            field=models.CharField(choices=[('unknown', 'Desconocido'), ('matched', 'Coincide'), ('mismatch', 'No coincide'), ('not_found', 'No encontrado')], default='unknown', max_length=20, verbose_name='Coincidencia RNC Certificado'),
        ),
    ]
