# Generated by Django 6.0 on 2026-06-15 01:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def backfill_legacy_ecf_certificates(apps, schema_editor):
    ECFIssuerConfig = apps.get_model('facturacion', 'ECFIssuerConfig')
    ECFCertificate = apps.get_model('facturacion', 'ECFCertificate')

    for issuer in ECFIssuerConfig.objects.exclude(certificate_path__isnull=True).exclude(certificate_path=''):
        uploaded_at = issuer.certificate_status_updated_at or django.utils.timezone.now()
        ECFCertificate.objects.get_or_create(
            company_id=issuer.company_id,
            issuer_id=issuer.id,
            environment=issuer.environment or 'testing',
            certificate_reference=issuer.certificate_path,
            defaults={
                'status': issuer.certificate_status or 'missing',
                'storage_backend': 'legacy_local',
                'password_secret_reference': issuer.certificate_password,
                'subject': issuer.certificate_subject,
                'issuer_name': issuer.certificate_issuer,
                'serial_number': issuer.certificate_serial_number,
                'fingerprint': issuer.certificate_fingerprint,
                'not_valid_before': issuer.certificate_not_valid_before,
                'not_valid_after': issuer.certificate_not_valid_after,
                'rnc_detected': issuer.certificate_rnc_detected,
                'rnc_match_status': issuer.certificate_rnc_match_status or 'unknown',
                'uploaded_at': uploaded_at,
                'activated_at': uploaded_at,
                'is_active': True,
                'notes': 'Backfill desde ECFIssuerConfig legacy.',
            },
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0040_ecfissuerconfig_certificate_rnc_detected_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ECFCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(choices=[('testing', 'Pruebas'), ('certification', 'Certificacion'), ('production', 'Produccion')], default='testing', max_length=20)),
                ('status', models.CharField(choices=[('missing', 'Faltante'), ('active', 'Activo'), ('expiring_soon', 'Por vencer'), ('expired', 'Vencido'), ('invalid', 'Inválido')], default='missing', max_length=20)),
                ('storage_backend', models.CharField(choices=[('legacy_local', 'Legacy local'), ('django_storage', 'Django storage'), ('kms', 'KMS / Secret manager'), ('vault', 'Vault')], default='legacy_local', max_length=40)),
                ('certificate_reference', models.CharField(max_length=500)),
                ('password_secret_reference', models.CharField(blank=True, max_length=500, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('issuer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('fingerprint', models.CharField(blank=True, max_length=128, null=True)),
                ('not_valid_before', models.DateTimeField(blank=True, null=True)),
                ('not_valid_after', models.DateTimeField(blank=True, null=True)),
                ('rnc_detected', models.CharField(blank=True, max_length=255, null=True)),
                ('rnc_match_status', models.CharField(choices=[('unknown', 'Desconocido'), ('matched', 'Coincide'), ('mismatch', 'No coincide'), ('not_found', 'No encontrado')], default='unknown', max_length=20)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ecf_certificates', to='facturacion.company')),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='facturacion.ecfissuerconfig')),
                ('previous_certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_certificates', to='facturacion.ecfcertificate')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_ecf_certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_active', '-uploaded_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('company', 'issuer', 'environment'), name='unique_active_ecf_certificate_per_issuer_env'), models.UniqueConstraint(condition=models.Q(('fingerprint__isnull', False), models.Q(('fingerprint', ''), _negated=True)), fields=('issuer', 'fingerprint'), name='unique_ecf_certificate_fingerprint_per_issuer')],
            },
        ),
        migrations.RunPython(backfill_legacy_ecf_certificates, noop_reverse),
    ]
