# Generated by Django 6.0 on 2026-06-16 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0041_ecfcertificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='DGIIPublicRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(db_index=True, max_length=120)),
                ('method', models.CharField(max_length=10)),
                ('content_type', models.CharField(blank=True, default='', max_length=120)),
                ('safe_headers', models.JSONField(blank=True, null=True)),
                ('body_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('body_preview', models.TextField(blank=True, default='')),
                ('rnc', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('remote_addr', models.GenericIPAddressField(blank=True, null=True)),
                ('response_status', models.PositiveSmallIntegerField()),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Request publico DGII',
                'verbose_name_plural': 'Requests publicos DGII',
                'ordering': ['-created_at'],
            },
        ),
    ]
