# Generated by Django 6.0 on 2026-06-19 19:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0042_dgiipublicrequestlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DGIICertificationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('imported', 'Importado')], default='imported', max_length=20)),
                ('source_filename', models.CharField(max_length=255)),
                ('file_sha256', models.CharField(db_index=True, max_length=64)),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('group_counts', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dgii_certification_plans', to='facturacion.company')),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dgii_certification_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plan de certificacion DGII',
                'verbose_name_plural': 'Planes de certificacion DGII',
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='DGIICertificationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecf_type', models.CharField(choices=[('31', 'Factura Credito Fiscal'), ('32', 'Factura Consumo'), ('33', 'Nota Debito'), ('34', 'Nota Credito'), ('41', 'Compras'), ('43', 'Gastos Menores'), ('44', 'Regimenes Especiales'), ('45', 'Gubernamental'), ('46', 'Exportaciones'), ('47', 'Pagos Exterior'), ('RFCE', 'Resumen Factura Consumo')], max_length=10)),
                ('dgii_group', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('generated', 'Generado'), ('signed', 'Firmado'), ('sent', 'Enviado'), ('accepted', 'Aceptado'), ('rejected', 'Rechazado')], default='pending', max_length=20)),
                ('encf', models.CharField(blank=True, default='', max_length=30)),
                ('document_type', models.CharField(blank=True, default='', max_length=120)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('receiver_rnc', models.CharField(blank=True, default='', max_length=20)),
                ('receiver_name', models.CharField(blank=True, default='', max_length=180)),
                ('observations', models.TextField(blank=True, default='')),
                ('source_sheet', models.CharField(max_length=120)),
                ('source_row', models.PositiveIntegerField()),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dgii_certification_items', to='facturacion.company')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='facturacion.dgiicertificationplan')),
            ],
            options={
                'verbose_name': 'Item de certificacion DGII',
                'verbose_name_plural': 'Items de certificacion DGII',
                'ordering': ['dgii_group', 'ecf_type', 'source_sheet', 'source_row'],
            },
        ),
        migrations.CreateModel(
            name='DGIICertificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('excel_imported', 'Excel importado'), ('plan_created', 'Plan creado'), ('item_detected', 'Item detectado'), ('import_error', 'Error de importacion')], max_length=40)),
                ('message', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dgii_certification_events', to='facturacion.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='facturacion.dgiicertificationitem')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='facturacion.dgiicertificationplan')),
            ],
            options={
                'verbose_name': 'Evento certificacion DGII',
                'verbose_name_plural': 'Eventos certificacion DGII',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='dgiicertificationitem',
            constraint=models.UniqueConstraint(fields=('plan', 'source_sheet', 'source_row'), name='unique_dgii_cert_item_source_row_per_plan'),
        ),
    ]
