# Generated by Django 6.0 on 2026-06-20 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0043_dgiicertificationplan_dgiicertificationitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dgiicertificationitem',
            name='generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dgiicertificationitem',
            name='generated_xml_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='dgiicertificationitem',
            name='generated_xml_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='dgiicertificationitem',
            name='generation_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='dgiicertificationevent',
            name='event_type',
            field=models.CharField(choices=[('excel_imported', 'Excel importado'), ('plan_created', 'Plan creado'), ('item_detected', 'Item detectado'), ('import_error', 'Error de importacion'), ('xml_generated', 'XML generado'), ('xml_generation_error', 'Error generacion XML')], max_length=40),
        ),
        migrations.AlterField(
            model_name='dgiicertificationitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('generated', 'Generado'), ('generation_error', 'Error generacion'), ('signed', 'Firmado'), ('sent', 'Enviado'), ('accepted', 'Aceptado'), ('rejected', 'Rechazado')], default='pending', max_length=20),
        ),
    ]
