# Generated by Django 6.0 on 2026-06-21 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0044_dgiicertificationitem_generated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DGIICertificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecf_type', models.CharField(choices=[('31', 'Factura Credito Fiscal'), ('32', 'Factura Consumo'), ('33', 'Nota Debito'), ('34', 'Nota Credito'), ('41', 'Compras'), ('43', 'Gastos Menores'), ('44', 'Regimenes Especiales'), ('45', 'Gubernamental'), ('46', 'Exportaciones'), ('47', 'Pagos Exterior'), ('RFCE', 'Resumen Factura Consumo')], max_length=10)),
                ('encf', models.CharField(blank=True, default='', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('generated', 'Documento generado'), ('generation_error', 'Error generacion')], default='pending', max_length=20)),
                ('xml_content', models.TextField(blank=True, default='')),
                ('xml_hash', models.CharField(blank=True, default='', max_length=64)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('generation_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dgii_certification_documents', to='facturacion.company')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certification_document', to='facturacion.dgiicertificationitem')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certification_documents', to='facturacion.dgiicertificationplan')),
            ],
            options={
                'verbose_name': 'Documento de certificacion DGII',
                'verbose_name_plural': 'Documentos de certificacion DGII',
                'ordering': ['plan_id', 'item__dgii_group', 'item__source_sheet', 'item__source_row'],
            },
        ),
    ]
