# Generated by Django 6.0 on 2026-06-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0046_dgiicertificationdocument_signed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dgiicertificationdocument',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dgiicertificationdocument',
            name='dgii_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dgiicertificationdocument',
            name='dgii_response_code',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='dgiicertificationdocument',
            name='dgii_response_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dgiicertificationdocument',
            name='dgii_status',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='dgiicertificationdocument',
            name='dgii_track_id',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='dgiicertificationdocument',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dgiicertificationdocument',
            name='submit_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dgiicertificationdocument',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dgiicertificationdocument',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('generated', 'Documento generado'), ('generation_error', 'Error generacion'), ('signed', 'Firmado'), ('signing_error', 'Error firma'), ('submitted', 'Enviado'), ('accepted', 'Aceptado'), ('rejected', 'Rechazado'), ('submit_error', 'Error envio')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='dgiicertificationevent',
            name='event_type',
            field=models.CharField(choices=[('excel_imported', 'Excel importado'), ('plan_created', 'Plan creado'), ('item_detected', 'Item detectado'), ('import_error', 'Error de importacion'), ('xml_generated', 'XML generado'), ('xml_generation_error', 'Error generacion XML'), ('document_signed', 'Documento firmado'), ('document_signing_error', 'Error firma documento'), ('document_submitted', 'Documento enviado'), ('document_accepted', 'Documento aceptado'), ('document_rejected', 'Documento rechazado'), ('document_submit_error', 'Error envio documento'), ('document_status_checked', 'Estado documento consultado')], max_length=40),
        ),
        migrations.AlterField(
            model_name='dgiicertificationitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('generated', 'Generado'), ('generation_error', 'Error generacion'), ('signing_error', 'Error firma'), ('signed', 'Firmado'), ('submit_error', 'Error envio'), ('sent', 'Enviado'), ('accepted', 'Aceptado'), ('rejected', 'Rechazado')], default='pending', max_length=20),
        ),
    ]
