# Generated by Django 6.0 on 2026-07-02 20:51

from django.db import migrations, models


def move_sequence_used_to_submit_conflict(apps, schema_editor):
    Document = apps.get_model('facturacion', 'DGIICertificationDocument')
    for document in Document.objects.select_related('item').all():
        message = f'{document.dgii_response_code or ""} {document.dgii_response_message or ""} {document.dgii_response or ""}'.lower()
        if '1209' not in message and 'secuencia ya ha sido utilizado' not in message:
            continue
        document.status = 'submit_conflict'
        document.dgii_status = 'Secuencia ya usada'
        document.dgii_response_code = '1209'
        if 'no cuenta como aceptada real' not in (document.dgii_response_message or ''):
            document.dgii_response_message = (
                'DGII indica que la secuencia ya fue utilizada; no cuenta como aceptada real. '
                f'{document.dgii_response_message or ""}'
            ).strip()
        document.accepted_at = None
        document.save(update_fields=[
            'status',
            'dgii_status',
            'dgii_response_code',
            'dgii_response_message',
            'accepted_at',
            'updated_at',
        ])
        if document.item_id:
            document.item.status = 'submit_conflict'
            document.item.save(update_fields=['status', 'updated_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0047_dgiicertificationdocument_accepted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dgiicertificationdocument',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('generated', 'Documento generado'), ('generation_error', 'Error generacion'), ('signed', 'Firmado'), ('signing_error', 'Error firma'), ('submitted', 'Enviado'), ('accepted', 'Aceptado'), ('rejected', 'Rechazado'), ('submit_error', 'Error envio'), ('submit_conflict', 'Secuencia ya usada')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='dgiicertificationitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('generated', 'Generado'), ('generation_error', 'Error generacion'), ('signing_error', 'Error firma'), ('signed', 'Firmado'), ('submit_error', 'Error envio'), ('sent', 'Enviado'), ('accepted', 'Aceptado'), ('rejected', 'Rechazado'), ('submit_conflict', 'Secuencia ya usada')], default='pending', max_length=20),
        ),
        migrations.RunPython(move_sequence_used_to_submit_conflict, migrations.RunPython.noop),
    ]
