# Generated by Codex on 2026-07-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0048_alter_dgiicertificationdocument_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dgiicertificationdocument',
            name='accepted_stale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dgiicertificationdocument',
            name='stale_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dgiicertificationdocument',
            name='stale_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
