# Generated by Django 6.0 on 2026-07-10 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0049_dgiicertificationdocument_accepted_stale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dgiicertificationdocument',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('generated', 'Documento generado'), ('generation_error', 'Error generacion'), ('signed', 'Firmado'), ('signing_error', 'Error firma'), ('submitted', 'Enviado'), ('accepted', 'Aceptado'), ('rejected', 'Rechazado'), ('submit_error', 'Error envio'), ('submit_conflict', 'Secuencia ya usada'), ('ready_for_portal_upload', 'Listo para cargar en portal'), ('uploaded_to_portal', 'Cargado en portal'), ('accepted_by_portal', 'Aceptado en portal')], default='pending', max_length=30),
        ),
    ]
