# Generated by Django 6.0 on 2026-07-11 03:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0050_alter_dgiicertificationdocument_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dgiicertificationevent',
            name='event_type',
            field=models.CharField(choices=[('excel_imported', 'Excel importado'), ('plan_created', 'Plan creado'), ('item_detected', 'Item detectado'), ('import_error', 'Error de importacion'), ('xml_generated', 'XML generado'), ('xml_generation_error', 'Error generacion XML'), ('document_signed', 'Documento firmado'), ('document_signing_error', 'Error firma documento'), ('document_submitted', 'Documento enviado'), ('document_accepted', 'Documento aceptado'), ('document_rejected', 'Documento rechazado'), ('document_submit_error', 'Error envio documento'), ('document_status_checked', 'Estado documento consultado'), ('dgii_reset_detected', 'Reinicio DGII detectado'), ('document_acceptance_stale', 'Aceptacion DGII obsoleta')], max_length=40),
        ),
        migrations.CreateModel(
            name='DGIICertificationCommercialApprovalPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_filename', models.CharField(max_length=255)),
                ('file_sha256', models.CharField(db_index=True, max_length=64)),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('imported', 'Importado'), ('processed', 'Procesado'), ('error', 'Error')], default='imported', max_length=20)),
                ('total_records', models.PositiveIntegerField(default=0)),
                ('approved_count', models.PositiveIntegerField(default=0)),
                ('rejected_count', models.PositiveIntegerField(default=0)),
                ('pending_count', models.PositiveIntegerField(default=0)),
                ('raw_summary', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dgii_commercial_approval_plans', to='facturacion.company')),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dgii_commercial_approval_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plan aprobacion comercial DGII',
                'verbose_name_plural': 'Planes aprobacion comercial DGII',
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='DGIICertificationCommercialApprovalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(blank=True, default='', max_length=20)),
                ('issuer_rnc', models.CharField(max_length=20)),
                ('encf', models.CharField(max_length=30)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('buyer_rnc', models.CharField(blank=True, default='', max_length=20)),
                ('dgii_status', models.CharField(choices=[('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('pendiente', 'Pendiente'), ('desconocido', 'Desconocido')], default='desconocido', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('commercial_approval_at', models.DateTimeField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('matched_document_type', models.CharField(blank=True, default='', max_length=80)),
                ('matched_document_id', models.PositiveIntegerField(blank=True, null=True)),
                ('match_status', models.CharField(choices=[('matched', 'Coincide'), ('not_found', 'No encontrado'), ('ambiguous', 'Ambiguo'), ('not_applicable', 'No aplica')], default='not_found', max_length=20)),
                ('match_observations', models.TextField(blank=True, default='')),
                ('source_row', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dgii_commercial_approval_items', to='facturacion.company')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='facturacion.dgiicertificationcommercialapprovalplan')),
            ],
            options={
                'verbose_name': 'Item aprobacion comercial DGII',
                'verbose_name_plural': 'Items aprobacion comercial DGII',
                'ordering': ['source_row', 'encf'],
            },
        ),
        migrations.CreateModel(
            name='DGIICertificationCommercialApprovalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('imported', 'Importacion'), ('replaced', 'Reemplazo'), ('structure_error', 'Error estructura'), ('not_found', 'No encontrado'), ('amount_mismatch', 'Diferencia monto'), ('rnc_mismatch', 'Diferencia RNC')], max_length=40)),
                ('message', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dgii_commercial_approval_events', to='facturacion.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='facturacion.dgiicertificationcommercialapprovalitem')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='facturacion.dgiicertificationcommercialapprovalplan')),
            ],
            options={
                'verbose_name': 'Evento aprobacion comercial DGII',
                'verbose_name_plural': 'Eventos aprobacion comercial DGII',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='dgiicertificationcommercialapprovalplan',
            constraint=models.UniqueConstraint(fields=('company', 'file_sha256'), name='unique_dgii_commercial_approval_file_per_company'),
        ),
        migrations.AddConstraint(
            model_name='dgiicertificationcommercialapprovalitem',
            constraint=models.UniqueConstraint(fields=('plan', 'encf'), name='unique_dgii_commercial_approval_encf_per_plan'),
        ),
    ]
