# Generated by Django 6.0 on 2026-07-11 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0051_alter_dgiicertificationevent_event_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dgiicertificationcommercialapprovalitem',
            name='approval_receiver_rnc',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
