# Generated by Django 6.0 on 2026-07-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0052_dgiicertificationcommercialapprovalitem_approval_receiver_rnc'),
    ]

    operations = [
        migrations.AddField(
            model_name='dgiicertificationcommercialapprovalitem',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dgiicertificationcommercialapprovalitem',
            name='dgii_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dgiicertificationcommercialapprovalitem',
            name='dgii_response_code',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='dgiicertificationcommercialapprovalitem',
            name='dgii_response_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dgiicertificationcommercialapprovalitem',
            name='dgii_track_id',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='dgiicertificationcommercialapprovalitem',
            name='generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dgiicertificationcommercialapprovalitem',
            name='generated_xml_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='dgiicertificationcommercialapprovalitem',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dgiicertificationcommercialapprovalitem',
            name='signature_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dgiicertificationcommercialapprovalitem',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dgiicertificationcommercialapprovalitem',
            name='signed_xml_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='dgiicertificationcommercialapprovalitem',
            name='signed_xml_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='dgiicertificationcommercialapprovalitem',
            name='source_approval_status',
            field=models.CharField(choices=[('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('pending', 'Pendiente'), ('unknown', 'Desconocido')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='dgiicertificationcommercialapprovalitem',
            name='submission_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dgiicertificationcommercialapprovalitem',
            name='submission_status',
            field=models.CharField(choices=[('pending', 'Por enviar'), ('generated', 'Generado'), ('signed', 'Firmado'), ('submitted', 'Enviado'), ('accepted', 'Aceptado DGII'), ('rejected', 'Rechazado DGII'), ('failed', 'Fallido')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='dgiicertificationcommercialapprovalitem',
            name='dgii_status',
            field=models.CharField(choices=[('aprobado', 'Aprobado legacy'), ('rechazado', 'Rechazado legacy'), ('pendiente', 'Pendiente legacy'), ('desconocido', 'Desconocido legacy')], default='desconocido', max_length=20),
        ),
    ]
