# Generated by Django 6.0 on 2026-08-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0053_dgiicertificationcommercialapprovalitem_accepted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronicfiscaldocument',
            name='submission_outcome',
            field=models.CharField(
                choices=[
                    ('not_started', 'No iniciado'),
                    ('in_flight', 'Envío en curso'),
                    ('unknown', 'Resultado de envío desconocido'),
                    ('confirmed', 'Envío confirmado por DGII'),
                    ('manual_review', 'Revisión manual requerida'),
                ],
                db_index=True,
                default='not_started',
                max_length=20,
                verbose_name='Resultado de Envío DGII',
            ),
        ),
        migrations.AddField(
            model_name='electronicfiscaldocument',
            name='submission_fingerprint',
            field=models.CharField(
                blank=True,
                db_index=True,
                default='',
                max_length=64,
                verbose_name='Huella SHA-256 del Envío',
            ),
        ),
        migrations.AddField(
            model_name='electronicfiscaldocument',
            name='submission_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inicio de Envío DGII'),
        ),
        migrations.AddField(
            model_name='electronicfiscaldocument',
            name='reconciliation_attempts',
            field=models.PositiveIntegerField(default=0, verbose_name='Intentos de Reconciliación DGII'),
        ),
        migrations.AddField(
            model_name='electronicfiscaldocument',
            name='last_reconciled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última Reconciliación DGII'),
        ),
        migrations.AddField(
            model_name='electronicfiscaldocument',
            name='requires_manual_review',
            field=models.BooleanField(default=False, verbose_name='Requiere Revisión Manual'),
        ),
        migrations.AddField(
            model_name='electronicfiscaldocument',
            name='manual_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Revisión Manual'),
        ),
    ]
