# Generated by Django 6.0 on 2026-08-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0054_electronicfiscaldocument_submission_reconciliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronicfiscaldocument',
            name='reconciliation_lease_until',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Lease de Reconciliación Hasta'),
        ),
        migrations.AddField(
            model_name='electronicfiscaldocument',
            name='reconciliation_lease_token',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Token de Lease de Reconciliación'),
        ),
        migrations.AlterField(
            model_name='ecfeventlog',
            name='event_type',
            field=models.CharField(
                choices=[
                    ('created', 'Creado'), ('queued', 'Encolado'),
                    ('xml_generated', 'XML Generado'), ('signed', 'Firmado'),
                    ('submitted', 'Enviado'), ('status_checked', 'Estado Consultado'),
                    ('retry_scheduled', 'Reintento Programado'), ('skipped', 'Omitido'),
                    ('inventory_restored', 'Inventario Restaurado'),
                    ('inventory_compensated', 'Inventario Compensado'),
                    ('manual_review', 'Revision Manual'),
                    ('multiple_track_ids_detected', 'Múltiples TrackID Detectados'),
                    ('accepted', 'Aceptado'), ('rejected', 'Rechazado'),
                    ('cancelled', 'Anulado'), ('error', 'Error'),
                ],
                max_length=30,
            ),
        ),
    ]
